os:
  - linux
  - osx
language: node_js

node_js:
  - '7'
  - '8'

script: ./test/travis-build.sh

cache:
  directories:
    - node_modules
    - components/anypoint/bower_components
    - components/default/bower_components
