os:
  - linux
  - osx
language: node_js

node_js:
  - '7'
  - '8'
  - '10'

sudo: required

before_script:
- npm install -g bower
- bower i
# - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

script: ./test/travis-build.sh

cache:
  directories:
    - node_modules
    - components/anypoint/bower_components
    - components/default/bower_components
