jobs:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: stable
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    language: node_js
    node_js: stable
    services:
    - docker
    - xvfb
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^\\d+\\.\\d+\\.\\d+$/"
install:
- npm install
script: "./test/travis-build.sh"
after_success:
- tasks/arc-publish.sh
env:
  global:
  # Mac
  - secure: SSAr0zXHZ7hhoOOciN5FtW0hcT+7xYFUyPSqguyLFGd+O3o1dvvFCqc783bIdeMZCvRwUhPuAFIVw3ykTUWTDCYKktSMjjjvI0S1pVixPdDaV883bk2Pq4hKEdJYaQK7ErbLOQd7uMW9Cqe2l/uQt21t4Ld3LeX6QMgM1IZLRdTIRjhUDQ0TeDVSStA4dMemUpTJ8Pf2PgwVcjxFbBb858OXplb+2VVGj0KQ3yz3/k5IF0X1qxaRMo9zT/bdB89bbD75c6+Pv7OwGR4p5nPFUBKnHNyOkUeE9NQF2GJzuBtGpM+Qc+SpDj0ToJcJ0a9ztccPbTZioaHxTLmDRBHjUqB49jSCC2W+Wilf6WrmqrdtFNfDml/40U/WDUhJflG6/qFBj6ogJ9qlqkpyJST09Csuj94feiCBSCY5ADosCLZZ6wosbJqE533CUnyWki/DsVJl4FSmM2K2/7Sj5YGc6EX6BOv80UXyNxZGaoF2GrdZ6hKvSyUtz/jtsw/GrEsC1rI0aoWXXmhxDbE3plAjSB54AG5Pzw8i7ROFWL5lbMB6I+UoEtw7g47V5o4j65rkNoOQp5vKb9g2JfkoAJ6+cEVR6TfsZ9dCD+eLWnOK8K/V1+H2U5RZgNQ3rGLDW7O3hf1TaNhHr6v1VzEoHr/RKsArLdjqnAJHCr+PLJElcBU=
  # GH token
  - secure: Evz9xCvbNhG7AKKKJIXtvSLBb6n8WCzNnqGevbgq8LhtZHYzt0SNDqbOs3701G/tzeOtueCdqARB13Xzt5TkTwWeDp+B9hQCKmT9uOKERMs9JK3EHnzdPJVSrIvcmp4X1M7RIEbqZ0rnn4wGtrwS6bbYqpTY+sRYyRoa2u2lrOVN4H9/BGiVPScBpZmbSxXlM5k2oJKv7pb2NV4NECU/CptEwV0DJHQnaQG1//mVYF+1LJSt9Ztqqk5qWVB/+cDBs49kJLjiv+s+LSzvRt+KLWt80/O6bjAXx2+bas2PMUDuj4/X2zTLH0dcU80MNMC8kukDbcKmRIbq7BQiqJvc1E9zhjSzIDGuUW9XvHbTFMw/+NfcQdiD/XAUKzjD9Gc0lllig0K7xeswhgtE55t4AkADQjFF9j0YqKMfYZ8kvDH8LiQfpQYRrXDh4fHzbKhe2yXsHArSbJV9p+Fl8UMct94im5VuLWghzMKf7HN5EUperl40FM4Hx7hwI5qhn/Ksp6/FHjkk1Xlwup9SNTKoDX6PmhCE8oWq0UGXVpb4FVOVSYBxLVnOMCThWZW/URF/BVHKtJFQF7sg+4hBLNQ90WlPAnun3enNUNpEDtXkapbDXW+SUfRu7Zm3YuT2muHSQIsbpC1CM7IIn+3g8xVuWRGNcUNUdsR63VPhgyZr/LU=
  # Windows
  - secure: L8M+lS+Ymr4RgIPd4QAvMSpmNN/ay2S8asQdkeNJpDf2C4sha+HI8WkH9qkRmsp79CK96zmM1wRhNgC49oRD/9r9GVQljMrtKa61e11diQqge7Xu4Kv1zs8m1yuFGRQUoxUdKZIVYnv0D8/5zwUQlQ27oHkkpxyeSkdPBAR/kVDRSlVwMsg/R3ZnXm4e6MNOfB02GXBvtXvYU11rRaoRHErKnywevDk+pOs8F0dom3E75JzBMB773PBrECH4PJjYKGSKRCjOP2o+1rXfNMoSc3o67N4uLPmVq/cLRRD8kliJNoWqKAATT3BjUE2oQeL7spyxnV25LZp7r7U0mzbFrX24TZQL3yZAEV/rQepqCWgzNsQMId67rn56jeUd3IoXHLsHzqy2YYJIB8xmbxd6n8x0SU8n+usBLXR55zT+eIQzCcdCLcRJncGxFWXa2HAwDIHNh5sNANYYLmDO1ZrxrCBQ0os8Jemkg6KwGiLauROJkSejWdWDs+aXdfhu5Fhs9xYE2kvB1WeCJIyyFFi3pmVmri2cJ7tez2gLZov6dfbRq/XAFidrEb7llXl754zkprXkW/NDfmaepJ8AXmeBkmo7ZXMlSMphALEG9r8nKFR3mbOiXt1YCqeP5MqYYV2wUUafL58iQiVPIDPV0ISRvyqHGz+OZ/T0kCDzXmyfJ4g=
