jobs:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: stable
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    language: node_js
    node_js: stable
    services:
    - docker
    - xvfb
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^\\d+\\.\\d+\\.\\d+$/"
install:
- npm install
script: "./test/travis-build.sh"
after_success:
- tasks/arc-publish.sh
env:
  global:
  - secure: vqjLjFS1r21KkSV6g5rrnHnEDvytxFZUZGglmVBfEMWMTLmUt6tpUOZ9fQhNK02Lwoqabx+jwqkqQH3n2Qh4rdgrHciaZz8rVpB+BNRbGpk8Av9pvJEFt5P2UUfjgthgBEUCAkcMlFAWvVgGoiaZPTLufxh9YZvjilG6QrZq6907+YZmxanFfQs/YpCwhG1S36BZ5ce3FxWk7z46DETD3LIe5ThImdmxruEv31F1pNNfInoDGg1qucQiZ2Icd6e+TK6tHH76KJbWc7kaJFSaubu1zIepmUNAxwdLN13nCPcxZaTkPs+LkCel3/C0hD/GLYEc48qC6zQDiQ61/JbUqtfZqShR5qpWhG0jETwpJqlUGNeWjO8KaPUcsolDy49Iiyy+ZMN8g7qiVcxqInLM3BT0Do3vyEZA3Z3WxXDF5wGeHy8PhUbFa3wZdRxtTgNoXCPJCPAzZIPYNUbby6auhWraBHU5UfyitH+CDP34FPaM9eG9TcJbEmdoA9rB9RYEH2T6OxGN/IntSuSP1cdkN/gi4c1ZsWlZSpCS9l5emakrGa4CMl7PKUBhefvKmn/UeYi+REHR2+iNOBYGBBAzfuwSn2iLg//Cg0SdDOs557vKFozVjM2u35Qp1zoncvEZWPSL3WaVGNzmlV35yjgculysZt1tEQpLWGIBmNjEa0c=
  - secure: rBRZZG8d933qFaCaakId+GMrZFHVPHr1hJtpy/2UN8wvqvnbo9ChHGer79cfhohc23Ligx+OhdSLSVl+bC4uesVX1kUssiFUFFDcYciEsJHplO1CtvPkApsEUJL3cndrvYrA52HPOmhtpuh74Npxdn8LrPyiNnLCTdNSt86dp/w8ve2N2ZI3CSEO9nG9L+rMqEkGC5fLQxXNsD4bJoDomg9tntXQYO2anyLnHa767SkbsbfHmrrF5BRPcX8i6/ZPtqG1hOnD72rHJwN0mpLJVsL7htbs9iyMkMciQn5j+BTfV00o51Id3rR0AxrAJUPfb+62i3s7vwJh9cyOTSJ7tBQSxe5EGa0gUlikHJ3elhDFylZXQM/Tmch5yJ0btNWQTsJI7ZwWe+RImDmPtWcNijxU144VdLq8nPz7rBuV4ouIgnnLA1QUT9IjS9vR09xa0DBH2Amjoea2bj7wHj86gfb/ECMkTfRysLrs+DVysC0pqAOONuvz6mBF7OLvK7uN08w6LG3VwwHJ28K52cudiHNv1NXv9hwWxPzizg3VG6WhTlA8y/wSoNDf3Q0UROfPouwx+AM+ojpM5gYVApAwHZvAjsn/Nu+lMQVT3xfnnr+SehTJprK+9Yv1HAFMJNFKbN71w7pdUx05B/YWxMxElg6Pp8s6mlntrsFbCNJ6lCo=
  - secure: g/NSFiqzCb/vkPnfxgmcdZOUYKjV07afE5FyqepQr1+9gBZ6rjsmU4RknrV/+sQgizuFV8Wtzav4fz1Ysm3yTclvO/bsfrstnHGoRCdy7AVTo3KjYmEl4CWFWLIO5bl2i/v5VV/8fHMIYyrKA0VI6sp1QG6okIuDv4lDs27aOiBkNtCSRj1XjnpGw07RIA7uDw/gk342uGKHbSZlpNuwCv6AREUoFFij9Rav+QBbN4WhPJIFu0gf8EpXket0b92SKNDdoSgyGDMDBcdcqi2CZC+BmX3P1hbiuKYOp++J2XUGVet8bGB21BsfBTGgaBwbzMun5GnnEsFfS/UC3QvbUBdR8l/YVNmBGWa2yZeWSTLg2OyvyCZWMnNWc6dFfyNLFsGosWf74v52Y+fe1thkDqeod5SO3j5BRgIqaiJ5aWZ3e1ylM3wF1s1yPznMxux7ATmLsCryUIvB42g90gRBrkykV/w75W4QLh7iKfyuNpyQ3ai1UT7A5gWIbp3EGzB7alTVPWp2xeAR8IXL/IsXQ1we/sTAdxWg5RC5oi9zBLGENub55T6NraBkAdB6KjbbAEEoQEjLTp8WJLm4T4rC4ocIItorwnjsdjyWujRj8AUTfvUsmhkzmD1+g23wqvVs2sNK6HyDajcOc929Jw/QAOBRRNdTvPnOEMJhqE9uO1w=
