matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: stable
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    sudo: required
    language: node_js
    node_js: stable
    services:
    - docker
    - xvfb
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
install:
- npm install
script: "./test/travis-build.sh"
after_success:
- tasks/arc-publish.sh
env:
  global:
  - secure: NQtwpDyG5qcPNDVJvHUn2LQKqAI3BYFektAQb7RyCD/eDlzA1b3Orv8nnOPmZ6H05YJBO00RRpvPDAc2944pm7XqY0HuDB0KBjUjb3kLAChiD9D7SKAnTJ4Lvjfyyf6eVXdDRBU5hTFKtsABfn/hIz+J/XVInDVaPOYIeTB70BsgMzkVlDj0hsyM2n7AvPzHupBsgpTL/hGNR0pm45oSV5c9mM72JGy84c6rAW01DLC7N6CgVkRNjAIQ4SYbZj57kO3WLXJ9Hryhqz5manq84R/j5Jg9XggR3+XCvloyFKXYO3n+ogw4zV3Ie81JDqbLJA4u2ayJ8h9wHaUWoSroW594xQchqsAVypnc/fgvHOxRrSozRDja3q9kKdJ/7nSOJ3k1jsy1gJEaDT0OO2py/OQ6F+1gfvMVmID30mL1m5UR9ARpwLyn+gezw4zvCt3JQv3WjzRZzsBhtCj5Mt75GRJK4bROsELO3tDLYzjewI/1tCw/xst097G5MCImVxepOrnlDguqij+0gpE10Pdwto/VUQBvlakLGXSF6CcatXiyIkwVpQEaKT9HGUHXXY51UoMwxS5CvzkvyAEzNam5/GRv6ifDJal0jHe4bLSUHJwC3CQDjZG3LVcIr+SpuEZ/Kq5/Kvr/1QoWAwoMBrCAkdoZmw7gyflm2d/pXsy9pBE=
  - secure: EBvXAmYLyceTXTWfjR8ygJBU1vGr+Ld9MgSTpBtS/pOjU4XOOH7flcGk+YbfFG/Gaejlpb50rejmvjBh/JBwRy9IUy3+EY1bNlQNLT+ywG/7y9i9BRrTkh6lnITWAA+fUDbqjgMqO77O5vN+DWKV9UcIp0u8WrrNJjJ2O2qJMdBVcRO3YMua7EXAAbEOkb2qHPqv8g3K5plhSlK2PnBJKcwrlIdVsSH9nrKhe++FOYwpyTX2AkqGY2BOom29wKtNy9CSy82XcmaofKF8VMn0AxYULmV0ocoNnyYO86Ex6PH/0iufpmuvPNlFIbaIXdzqa8SNqci7Z8nkizNAOW5VDdCoVtYIzgI5xHq/Oht56yN648fY/LNU9YrDG8L/71CPdGLWkYZjd+nrSY3E+nTJvYTsSvq6abZWpUU8Sss41SeX8kjVDNNbLOXb0vCOLLUTHwMx90yNNwtudpwmw1kPmZ8nAQCSN69Kb4opG90LoxSvFI61Oku2pQHb74pOrRbiMVdOTprSUFSQTnJ+D3PUIasjrh+pehNEQ0RzEE0Zj8yHq9xlFitpOilcAs+BohdjWLqMxPnJhMDHN/+m/5b8bLo8pILyfZCOM3ksYDR00b48rJPKRJbJsSXOIs292b8iFqpwoUFZxe3AMFNjlVsZBtdzpRyjtKheggT39Z4x+ZQ=
  - secure: vqjLjFS1r21KkSV6g5rrnHnEDvytxFZUZGglmVBfEMWMTLmUt6tpUOZ9fQhNK02Lwoqabx+jwqkqQH3n2Qh4rdgrHciaZz8rVpB+BNRbGpk8Av9pvJEFt5P2UUfjgthgBEUCAkcMlFAWvVgGoiaZPTLufxh9YZvjilG6QrZq6907+YZmxanFfQs/YpCwhG1S36BZ5ce3FxWk7z46DETD3LIe5ThImdmxruEv31F1pNNfInoDGg1qucQiZ2Icd6e+TK6tHH76KJbWc7kaJFSaubu1zIepmUNAxwdLN13nCPcxZaTkPs+LkCel3/C0hD/GLYEc48qC6zQDiQ61/JbUqtfZqShR5qpWhG0jETwpJqlUGNeWjO8KaPUcsolDy49Iiyy+ZMN8g7qiVcxqInLM3BT0Do3vyEZA3Z3WxXDF5wGeHy8PhUbFa3wZdRxtTgNoXCPJCPAzZIPYNUbby6auhWraBHU5UfyitH+CDP34FPaM9eG9TcJbEmdoA9rB9RYEH2T6OxGN/IntSuSP1cdkN/gi4c1ZsWlZSpCS9l5emakrGa4CMl7PKUBhefvKmn/UeYi+REHR2+iNOBYGBBAzfuwSn2iLg//Cg0SdDOs557vKFozVjM2u35Qp1zoncvEZWPSL3WaVGNzmlV35yjgculysZt1tEQpLWGIBmNjEa0c=
before_install:
- openssl aes-256-cbc -K $encrypted_cb8606543db7_key -iv $encrypted_cb8606543db7_iv
  -in certs.tar.enc -out certs.tar -d
- tar xvf certs.tar
