matrix:
  allow_failures:
    - nodejs_version: 8
    - nodejs_version: 10
install:
  - set CI=true
  - npm install
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - set NODE_ENV=test
  - set ELECTRON_PATH=node_modules\\.bin\\electron
  - node_modules\\.bin\\electron-mocha test\\**\\*.main.spec.js scripts\\packages\\**\\*.main.spec.js
