appId: "com.mulesoft.arc"
productName: AdvancedRestClient
artifactName: 'arc-nightly-${version}-${arch}.${ext}'
asar: true
copyright: Copyright © 2018 Mulesoft
generateUpdatesFilesForAllChannels: true
files:
  - filter:
    - app.html
    - app.js
    - main.js
    - task-manager.html
    - package.json
    - assets/
    - bower_components/
    - node_modules/
    - menus/
    - scripts/
    - src/
    - appresources/
mac:
  category: public.app-category.developer-tools
  icon: build/icon.icns
  target:
    - target: dmg
      arch:
        - x64
    - target: zip
      arch:
        - x64
dmg:
  contents:
    - x: 110
      'y': 150
    - x: 240
      'y': 150
      type: link
      path: /Applications
linux:
  category: Development
  target:
    - target: deb
      arch:
        - x64
        - ia32
    - target: rpm
      arch:
        - x64
        - ia32
    - target: tar.gz
      arch:
        - x64
        - ia32
    - target: AppImage
      arch:
        - x64
        - ia32
  vendor: Mulesoft
  synopsis: A developer tool to test HTTP requests
  artifactName: 'arc-linux-nightly-${version}-${arch}.${ext}'
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
appx:
  applicationId: AdvancedRestClient
  identityName: 48695PawelPsztyc.advanced-rest-client
  publisher: CN=D213CA20-88CE-42AC-A9F2-C5D41BF04550
  publisherDisplayName: Pawel Psztyc
publish:
  - provider: github
    owner: advanced-rest-client
    repo: arc-electron
    releaseType: draft
protocols:
  name: ARC file open
  schemes:
    - arc-file
nsis:
  installerIcon: build/icon.ico
  uninstallerIcon: build/icon.ico
  artifactName: 'arc-setup-nightly-${arch}.${ext}'
  shortcutName: ARC
